[package]
name = "g"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_bindgen = "0.7.0"
serde = { version = "1", features = ["derive"] }

[lib]
crate-type = ["cdylib"]