name: Release libs

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag name"
        required: true

jobs:
  build:
    name: Release libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: 0.9.0

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Build MacOS x86_64
      if: runner.os == 'MacOS'
      run: |
        mv target/release/libx.dylib libx_x86_64.dylib

    - name: Upload MacOS x86_64
      if: runner.os == 'MacOS'
      uses: svenstaro/upload-release-action@v2
      with:
        file: libx_x86_64.dylib
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Build MacOS aarch64 lib
      if: runner.os == 'Linux'
      run: |
        rustup target add aarch64-apple-darwin
        cargo install cargo-zigbuild
        cargo zigbuild --release --target aarch64-apple-darwin
        mv target/aarch64-apple-darwin/release/libx.dylib libx_aarch64.dylib

    - name: Upload MacOS aarch64
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: libx_aarch64.dylib
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release Linux lib
      if: runner.os == 'Linux'
      uses: svenstaro/upload-release-action@v2
      with:
        file: target/release/libx.so
        tag: ${{ github.event.inputs.tag }}
        overwrite: true

    - name: Release Windows lib
      if: runner.os == 'Windows'
      uses: svenstaro/upload-release-action@v2
      with:
        file: target/release/x.dll
        tag: ${{ github.event.inputs.tag }}
        overwrite: true