name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Setup repo
      uses: actions/checkout@v3

    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - if: runner.os == 'Windows'
      run: (Get-Command -Name "deno").Source

    - uses: actions/checkout@v3
    - name: Run
      run: cargo run

    # - name: Deno Run
    #   run: deno run -A --unstable a.ts
      
